project_id = "iplsmxbiwtsicdklvpah"

[functions.fortnox-sync]
verify_jwt = true

[functions.fortnox-auth]
verify_jwt = true

[functions.fortnox-callback]
verify_jwt = false

[functions.fortnox-import-range]
verify_jwt = false

[functions.fortnox-status]
verify_jwt = true

[functions.sie-import]
verify_jwt = true

[functions.budget-api]
verify_jwt = false
